proxyPort: "7080"
certPath : /path/to/server.crt
keyPath: /path/to/server.key
endpoints:
  - backendUrl : http://localhost:9080
    proxyEndpoint : /one
  - backendUrl: https://localhost:9081
    proxyEndpoint: /two