proxyPort: "7080"
certPath : ./Certs/server.crt
keyPath: ./Certs/server.key
endpoints:
  - backendUrl : http://localhost:9080
    proxyEndpoint : /sample
  - backendUrl: https://localhost:9081
    proxyEndpoint: /another
